version: 2

sources:
  - name: vdidier
    database: VDIDIER
    schema: VD  
    tables:
      - name: ORDERS
      - name: CUSTOMERS
      - name: ORDER_ITEMS
      - name: PRODUCTS


  